### ISSUE TITLE
Error: References to undefined settings

### ISSUE THREAD

**Issue by LLCampos** [AlexITC/chrome-scalajs-template#18]
If I follow [the steps in the Get Started](https://github.com/AlexITC/chrome-scalajs-template#get-started) I get an error like [this](https://github.com/scalacenter/scalajs-bundler/issues/373) one.

Upgrading `sbt-scalajs-bundler` to `0.20.0` seems to solve it!

**Comment by AlexITC** [comment]
Thanks, I started accepting PRs from scalasteward without a proper CI which may have broke the build.

**Comment by AlexITC** [comment]
Fixed, thanks!
