### ISSUE TITLE
Thanks for this template!

### ISSUE THREAD

**Issue by phdoerfler** [AlexITC/chrome-scalajs-template#38]
I can tell a lot of work went into this and I doubt I would have had the patience to figure all of this out by myself from 0, so thanks!

**Comment by AlexITC** [comment]
I'm glad it helped, there are definitely many potential improves which I'll be likely work in once this migrates to Scala 3.

**Comment by phdoerfler** [comment]
Yeah, I was already tempted to turn it into a giter8 template to remove the sed invocation, but I figured I should first try to use it before doing something like that.

**Comment by AlexITC** [comment]
Once you build something, it would be nice you share it to add it to the adopters list

**Comment by phdoerfler** [comment]
Good idea! In fact, despite me never having written a browser extension before, thanks to your template in just a few hours I managed to overlay a smiley face on the [komoot.com](https://www.komoot.com/plan) map:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/163428/122729086-13344300-d279-11eb-96ce-0257e566b37d.png">
The biggest pain points were figuring out how to access the page's DOM and how to wait until the page is ready for my modifications. Both of which are unrelated to Scala.js or the template of course.
Turns out, the former you can easily do just by using `document`. Just like you do when you write regular Scala.js code that runs in the browser. And it's even mentioned in the docs linked in the readme.
The latter can easily be done using a `MutationObserver` in my case since I need to wait for some other javascript code on the page to do its magic.
I believe both things would be interesting for others to learn from. So, yes, definitely on my want-to-contribute list!
